parameters:
  num_objects: 1
  # Количество различных геометрических тел
  num_classes: 4
  # Параметры генератора для куба
  # 1 - Cube
  # 2 - Cone
  # 3 - Ellipsoid
  # 4 - Cylinder

    # 1 - Micro
    # 2 - Small
    # 3 - Medium
    # 4 - Big
    # 5 - Large
  1:
    depth_min_z: 3
    depth_max_z: 7
    num_subcls: 5
    1:
      min_loc_xy: -6
      max_loc_xy: 6
      min_scale_xy: 0.1
      max_scale_xy: 0.5
      min_scale_z: 0.1
      max_scale_z: 0.4
    2:
      min_loc_xy: -5
      max_loc_xy: 5
      min_scale_xy: 0.6
      max_scale_xy: 1
      min_scale_z: 0.2
      max_scale_z: 0.9
    3:
      min_loc_xy: -4
      max_loc_xy: 4
      min_scale_xy: 1.1
      max_scale_xy: 1.5
      min_scale_z: 0.1
      max_scale_z: 1
    4:
      min_loc_xy: -2
      max_loc_xy: 2
      min_scale_xy: 1.6
      max_scale_xy: 3
      min_scale_z: 0.3
      max_scale_z: 2
    5:
      min_loc_xy: 0
      max_loc_xy: 0
      min_scale_xy: 3
      max_scale_xy: 5
      min_scale_z: 1
      max_scale_z: 3
  # Параметры генератора для конуса
  2:
    depth_min_z: 3
    depth_max_z: 7
    num_subcls: 5
    1:
      min_loc_xy: -6
      max_loc_xy: 6
      min_scale_xy: 0.25
      max_scale_xy: 0.7
      min_scale_z: 0.1
      max_scale_z: 0.4
    2:
      min_loc_xy: -5
      max_loc_xy: 5
      min_scale_xy: 0.75
      max_scale_xy: 1.25
      min_scale_z: 0.2
      max_scale_z: 0.9
    3:
      min_loc_xy: -4
      max_loc_xy: 4
      min_scale_xy: 1.3
      max_scale_xy: 1.8
      min_scale_z: 0.1
      max_scale_z: 1
    4:
      min_loc_xy: -2
      max_loc_xy: 2
      min_scale_xy: 1.85
      max_scale_xy: 3
      min_scale_z: 0.3
      max_scale_z: 2
    5:
      min_loc_xy: -1
      max_loc_xy: 1
      min_scale_xy: 3
      max_scale_xy: 5.5
      min_scale_z: 1
      max_scale_z: 3
  # Параметры генератора для сферы
  3:
    depth_min_z: 3
    depth_max_z: 7
    num_subcls: 5
    1:
      min_loc_xy: -6
      max_loc_xy: 6
      min_scale_xy: 0.2
      max_scale_xy: 0.6
      min_scale_z: 0.1
      max_scale_z: 0.4
    2:
      min_loc_xy: -5
      max_loc_xy: 5
      min_scale_xy: 0.65
      max_scale_xy: 1
      min_scale_z: 0.2
      max_scale_z: 0.9
    3:
      min_loc_xy: -4
      max_loc_xy: 4
      min_scale_xy: 1
      max_scale_xy: 1.6
      min_scale_z: 0.1
      max_scale_z: 1
    4:
      min_loc_xy: -2
      max_loc_xy: 2
      min_scale_xy: 1.7
      max_scale_xy: 2.5
      min_scale_z: 1
      max_scale_z: 2.5
    5:
      min_loc_xy: -1
      max_loc_xy: 1
      min_scale_xy: 3.5
      max_scale_xy: 6
      min_scale_z: 2
      max_scale_z: 4
  # Параметры генератора для цилиндра
  4:
    depth_min_z: 3
    depth_max_z: 7
    num_subcls: 5
    1:
      min_loc_xy: -6
      max_loc_xy: 6
      min_scale_xy: 0.1
      max_scale_xy: 0.5
      min_scale_z: 0.1
      max_scale_z: 0.4
    2:
      min_loc_xy: -5
      max_loc_xy: 5
      min_scale_xy: 0.6
      max_scale_xy: 1
      min_scale_z: 0.2
      max_scale_z: 0.9
    3:
      min_loc_xy: -4
      max_loc_xy: 4
      min_scale_xy: 1.1
      max_scale_xy: 1.5
      min_scale_z: 0.1
      max_scale_z: 1
    4:
      min_loc_xy: -2
      max_loc_xy: 2
      min_scale_xy: 1.6
      max_scale_xy: 3
      min_scale_z: 0.3
      max_scale_z: 2
    5:
      min_loc_xy: -1
      max_loc_xy: 1
      min_scale_xy: 3
      max_scale_xy: 5
      min_scale_z: 1
      max_scale_z: 3
